### ISSUE TITLE
timers just continue, never processes. 

### ISSUE THREAD

**Issue by JustCann** [numz/sd-wav2lip-uhq#102]
![issue](https://github.com/numz/sd-wav2lip-uhq/assets/84952060/2e7cbfbd-777a-4874-a6ca-f2c9fb76b45d)

Hello!

So I've been using this for some time now, I was able to use this seven times in a row before all of a sudden it no longer processed any video. I've been all the tricks that I can think of, including using the rescale slider, with no success. I am not even sure why all of a sudden it's no longer processing and the timers continue without anything actually occurring.

Your help is appreciated, thank you very much!

**Comment by saiyi123** [comment]
Make sure that all your model files are placed in the specified location. If there is no wav2lip model file, the background will not prompt an error, and the front-end display will always be running.
![无标题](https://github.com/numz/sd-wav2lip-uhq/assets/101044814/a8a34cde-e33b-4e51-ae84-5280fa94cbc5)

**Comment by JustCann** [comment]
I went back to this project and confirmed they were missing (odd as I never deleted them) but upon restarting I was experiencing the same issue. So I tried git checkout https://github.com/numz/sd-wav2lip-uhq/commit/2283dacdbf0b215fb05e9a18ed828a78d01ef55d and still getting this issue. Could this be due to length of video??

**Comment by JustCann** [comment]
I decided to cut the video in half (2 miniute video) and it started to process. However, I am now getting this error 

[INFO] Loading the predictor...
Traceback (most recent call last):
  File "C:\Users\alexi\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\alexi\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\alexi\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\alexi\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\alexi\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\alexi\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\alexi\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\alexi\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 89, in generate
    return w2luhq.execute()
  File "C:\Users\alexi\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\wav2lip\wav2lip_uhq.py", line 118, in execute
    detector, predictor = self.initialize_dlib_predictor()
  File "C:\Users\alexi\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\wav2lip\wav2lip_uhq.py", line 95, in initialize_dlib_predictor
    predictor = dlib.shape_predictor(self.wav2lip_folder + "/predicator/shape_predictor_68_face_landmarks.dat")
RuntimeError: Error deserializing object of type int
