### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by enragedshoe** [numz/sd-wav2lip-uhq#105]
When attempting to generate, the process dies on "ValueError: max() arg is an empty sequence.

----

Log:

Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\123/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\123/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\123/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\123/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\123/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Reading video frames for face swap...
E:\stable-diffusion-webui\venv\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 158, in generate
    video = face_swap.generate()
  File "E:\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\faceswap\swap.py", line 205, in generate
    image_restored = modules.face_restoration.restore_faces(face_swapped)
  File "E:\stable-diffusion-webui\modules\face_restoration.py", line 19, in restore_faces
    return face_restorer.restore(np_image)
  File "E:\stable-diffusion-webui\modules\gfpgan_model.py", line 121, in restore
    return gfpgan_fix_faces(np_image)
  File "E:\stable-diffusion-webui\modules\gfpgan_model.py", line 60, in gfpgan_fix_faces
    model = gfpgann()
  File "E:\stable-diffusion-webui\modules\gfpgan_model.py", line 38, in gfpgann
    latest_file = max(gfp_models, key=os.path.getctime)
ValueError: max() arg is an empty sequence

----

PC:

Windows 11
13900K
RTX 3090
64GB Memory

----

PIP List:

absl-py                   2.1.0
accelerate                0.21.0
addict                    2.4.0
aenum                     3.1.15
aiofiles                  23.2.1
aiohttp                   3.9.1
aiosignal                 1.3.1
albumentations            1.3.1
altair                    5.2.0
antlr4-python3-runtime    4.9.3
anyio                     3.7.1
appdirs                   1.4.4
async-timeout             4.0.3
attrs                     23.2.0
audioread                 3.0.1
basicsr                   1.4.2
beautifulsoup4            4.12.3
blendmodes                2022
boto3                     1.34.29
botocore                  1.34.29
certifi                   2023.11.17
cffi                      1.16.0
charset-normalizer        3.3.2
clean-fid                 0.1.35
click                     8.1.7
clip                      1.0
colorama                  0.4.6
coloredlogs               15.0.1
contourpy                 1.2.0
cycler                    0.12.1
Cython                    3.0.8
decorator                 5.1.1
deprecation               2.1.0
dlib-bin                  19.24.2
easydict                  1.11
einops                    0.4.1
encodec                   0.1.1
exceptiongroup            1.2.0
facexlib                  0.3.0
fastapi                   0.94.0
ffmpy                     0.3.1
filelock                  3.13.1
filterpy                  1.4.5
flatbuffers               23.5.26
fonttools                 4.47.2
frozenlist                1.4.1
fsspec                    2023.12.2
ftfy                      6.1.3
funcy                     2.0
future                    0.18.3
gdown                     5.0.1
gfpgan                    1.3.8
gitdb                     4.0.11
GitPython                 3.1.32
gradio                    3.41.2
gradio_client             0.5.0
grpcio                    1.60.0
h11                       0.12.0
httpcore                  0.15.0
httpx                     0.24.1
huggingface-hub           0.20.3
humanfriendly             10.0
idna                      3.6
ifnude                    0.0.3
imageio                   2.33.1
imageio-ffmpeg            0.4.9
importlib-metadata        7.0.1
importlib-resources       6.1.1
imutils                   0.5.4
inflection                0.5.1
insightface               0.7.3
Jinja2                    3.1.3
jmespath                  1.0.1
joblib                    1.3.2
jsonmerge                 1.8.0
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
kornia                    0.6.7
lark                      1.1.2
lazy_loader               0.3
librosa                   0.10.0.post2
lightning-utilities       0.10.1
llvmlite                  0.41.1
lmdb                      1.4.1
lpips                     0.1.4
Markdown                  3.5.2
MarkupSafe                2.1.4
matplotlib                3.8.2
mpmath                    1.3.0
msgpack                   1.0.7
multidict                 6.0.4
networkx                  3.2.1
numba                     0.58.1
numpy                     1.23.5
omegaconf                 2.2.3
onnx                      1.14.0
onnxruntime               1.15.0
onnxruntime-gpu           1.15.0
open-clip-torch           2.20.0
opencv-contrib-python     4.9.0.80
opencv-python             4.9.0.80
opencv-python-headless    4.9.0.80
orjson                    3.9.12
packaging                 23.2
pandas                    2.2.0
piexif                    1.1.3
Pillow                    9.5.0
pip                       22.3.1
platformdirs              4.1.0
pooch                     1.6.0
prettytable               3.9.0
protobuf                  4.25.2
psutil                    5.9.5
pycparser                 2.21
pydantic                  1.10.14
pydub                     0.25.1
pyparsing                 3.1.1
pyreadline3               3.4.1
PySocks                   1.7.1
python-dateutil           2.8.2
python-multipart          0.0.6
pytorch-lightning         1.9.4
pytz                      2023.3.post1
PyWavelets                1.5.0
PyYAML                    6.0.1
qudida                    0.0.4
realesrgan                0.3.0
referencing               0.32.1
regex                     2023.12.25
requests                  2.31.0
resize-right              0.0.2
rpds-py                   0.17.1
s3transfer                0.10.0
safetensors               0.3.1
scikit-image              0.21.0
scikit-learn              1.4.0
scipy                     1.12.0
semantic-version          2.10.0
sentencepiece             0.1.99
setuptools                65.5.0
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.0
soundfile                 0.12.1
soupsieve                 2.5
soxr                      0.3.7
starlette                 0.26.1
suno-bark                 0.0.1a0
sympy                     1.12
tb-nightly                2.16.0a20240127
tensorboard-data-server   0.7.2
tf_keras-nightly          2.16.0.dev2024012710
threadpoolctl             3.2.0
tifffile                  2023.12.9
timm                      0.9.2
tokenizers                0.13.3
tomesd                    0.1.3
tomli                     2.0.1
toolz                     0.12.1
torch                     2.1.2+cu118
torchaudio                2.1.2+cu118
torchdiffeq               0.2.3
torchmetrics              1.3.0.post0
torchsde                  0.2.6
torchvision               0.16.2+cu118
tqdm                      4.66.1
trampoline                0.1.2
transformers              4.30.2
typing_extensions         4.9.0
tzdata                    2023.4
urllib3                   2.0.7
uvicorn                   0.27.0
wcwidth                   0.2.13
websockets                11.0.3
Werkzeug                  3.0.1
yapf                      0.40.2
yarl                      1.9.4
zipp                      3.17.0

**Comment by mantosssss** [comment]
same over here. The problem arises only using GFPGAN for face restoration. No problem with CodeFormer

**Comment by yevvonlim** [comment]
i managed this problem by manually deleting _**stable-diffusion-webui/models/GFPGAN**_ directory. WebUI will automatically redownload the GFPGAN model in next run

**Comment by lj267lj267** [comment]
i managed this problem by manually copying gfpgan model file to model\GFPGAN\  ,filename is GFPGANv1.4.pth and alignment_WFLW_4HG.pth
