### ISSUE TITLE
What is the required CUDA version to run this repo reliably?

### ISSUE THREAD

**Issue by aerinkim** [numz/sd-wav2lip-uhq#106]
Hi, I just downgraded cuda to 11.2 to run faceswap as requirement however, I'm getting complaints:

```
[~/Projects/a1111]
$ ./webui.sh

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on ubuntu user
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Cannot locate TCMalloc (improves CPU memory usage)
Python 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:33)
[GCC 9.3.0]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Installing wav2lip_uhq requirement: librosa==0.10.0.post2
Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git
Installing wav2lip_uhq requirement: insightface==0.7.3
Installing wav2lip_uhq requirement: onnx==1.14.0
Installing wav2lip_uhq requirement: onnxruntime==1.15.0
Installing wav2lip_uhq requirement: onnxruntime-gpu==1.15.0
Installing wav2lip_uhq requirement: opencv-python>=4.8.0
Launching Web UI with arguments:
Traceback (most recent call last):
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/launch.py", line 44, in main
    start()
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/modules/launch_utils.py", line 460, in start
    import webui
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/modules/initialize.py", line 16, in imports
    import pytorch_lightning  # noqa: F401
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/utilities/types.py", line 27, in <module>
    from torchmetrics import Metric
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/__init__.py", line 22, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/utilities/data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _TORCH_GREATER_EQUAL_1_13, _XLA_AVAILABLE
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/utilities/imports.py", line 51, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/lightning_utilities/core/imports.py", line 77, in compare_version
    pkg = importlib.import_module(package)
  File "/opt/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import (  # noqa: F401
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchaudio/_extension/__init__.py", line 45, in <module>
    _load_lib("libtorchaudio")
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchaudio/_extension/utils.py", line 64, in _load_lib
    torch.ops.load_library(path)
  File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.12: cannot open shared object file: No such file or directory
```

Any solutions to this?

**Comment by hotdogarea** [comment]
> Hi, I just downgraded cuda to 11.2 to run faceswap as requirement however, I'm getting complaints:
> 
> ```
> [~/Projects/a1111]
> $ ./webui.sh
> 
> ################################################################
> Install script for stable-diffusion + Web UI
> Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
> ################################################################
> 
> ################################################################
> Running on ubuntu user
> ################################################################
> 
> ################################################################
> Create and activate python venv
> ################################################################
> 
> ################################################################
> Launching launch.py...
> ################################################################
> Cannot locate TCMalloc (improves CPU memory usage)
> Python 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:33)
> [GCC 9.3.0]
> Version: v1.7.0
> Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
> Installing wav2lip_uhq requirement: librosa==0.10.0.post2
> Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git
> Installing wav2lip_uhq requirement: insightface==0.7.3
> Installing wav2lip_uhq requirement: onnx==1.14.0
> Installing wav2lip_uhq requirement: onnxruntime==1.15.0
> Installing wav2lip_uhq requirement: onnxruntime-gpu==1.15.0
> Installing wav2lip_uhq requirement: opencv-python>=4.8.0
> Launching Web UI with arguments:
> Traceback (most recent call last):
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/launch.py", line 48, in <module>
>     main()
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/launch.py", line 44, in main
>     start()
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/modules/launch_utils.py", line 460, in start
>     import webui
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/webui.py", line 13, in <module>
>     initialize.imports()
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/modules/initialize.py", line 16, in imports
>     import pytorch_lightning  # noqa: F401
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
>     from pytorch_lightning.callbacks import Callback  # noqa: E402
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
>     from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
>     from pytorch_lightning.callbacks.callback import Callback
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
>     from pytorch_lightning.utilities.types import STEP_OUTPUT
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/utilities/types.py", line 27, in <module>
>     from torchmetrics import Metric
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/__init__.py", line 22, in <module>
>     from torchmetrics import functional  # noqa: E402
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
>     from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
>     from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
>     from torchmetrics.utilities import rank_zero_warn
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
>     from torchmetrics.utilities.checks import check_forward_full_state_property
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 25, in <module>
>     from torchmetrics.metric import Metric
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/metric.py", line 30, in <module>
>     from torchmetrics.utilities.data import (
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/utilities/data.py", line 22, in <module>
>     from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _TORCH_GREATER_EQUAL_1_13, _XLA_AVAILABLE
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/utilities/imports.py", line 51, in <module>
>     _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/lightning_utilities/core/imports.py", line 77, in compare_version
>     pkg = importlib.import_module(package)
>   File "/opt/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
>     from . import (  # noqa: F401
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchaudio/_extension/__init__.py", line 45, in <module>
>     _load_lib("libtorchaudio")
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchaudio/_extension/utils.py", line 64, in _load_lib
>     torch.ops.load_library(path)
>   File "/home/ubuntu/Projects/a1111/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/_ops.py", line 643, in load_library
>     ctypes.CDLL(path)
>   File "/opt/conda/lib/python3.9/ctypes/__init__.py", line 382, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: libcudart.so.12: cannot open shared object file: No such file or directory
> ```
> 
> Any solutions to this?

12.1
