### ISSUE TITLE
No module named 'scripts.wav2lip_uhq_extend_paths'

### ISSUE THREAD

**Issue by emourdavid** [numz/sd-wav2lip-uhq#109]
Hi Numz,

I got error regarding to this scripts.wav2lip_uhq_extend_paths when I start A1111 from v1.7 up to now. Would you please check this. I see this error happened few months ago.

Thanks so much.

Error loading script: ui.py
    Traceback (most recent call last):
      File "C:\Users\xxx\Documents\sd_webui_forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\xxx\Documents\sd_webui_forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\xxx\Documents\sd_webui_forge\extensions\sd-wav\scripts\ui.py", line 2, in <module>
        from scripts.wav2lip_uhq_extend_paths import wav2lip_uhq_sys_extend
    ModuleNotFoundError: No module named 'scripts.wav2lip_uhq_extend_paths'

**Comment by emourdavid** [comment]
I figure out my folder not sync after git pull. I reset this and get all new updates. Fix done. Thanks
