### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by hotdogarea** [numz/sd-wav2lip-uhq#111]
PS F:\AI\SD\stable-diffusion-webui> .\webui.bat --no-download-sd-model --xformers --share --listen --enable-insecure-extension-access --skip-torch-cuda-test
venv "F:\AI\SD\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.8.0
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
*** Error running install.py for extension F:\AI\SD\stable-diffusion-webui\extensions\sd-wav2lip-uhq.
*** Command: "F:\AI\SD\stable-diffusion-webui\venv\Scripts\python.exe" "F:\AI\SD\stable-diffusion-webui\extensions\sd-wav2lip-uhq\install.py"
*** Error code: 1
*** stdout: Installing wav2lip_uhq requirement: librosa==0.10.0.post2
*** Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git
*** Installing wav2lip_uhq requirement: insightface==0.7.3
***
*** stderr: Traceback (most recent call last):
***   File "F:\AI\SD\stable-diffusion-webui\extensions\sd-wav2lip-uhq\install.py", line 17, in <module>
***     launch.run_pip(f"install {lib}", f"wav2lip_uhq requirement: {lib}")
***   File "F:\AI\SD\stable-diffusion-webui\modules\launch_utils.py", line 143, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "F:\AI\SD\stable-diffusion-webui\modules\launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install wav2lip_uhq requirement: insightface==0.7.3.
*** Command: "F:\AI\SD\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install insightface==0.7.3 --prefer-binary
*** Error code: 1
*** stdout: Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
*** Collecting insightface==0.7.3
***   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0b/8d/0f4af90999ca96cf8cb846eb5ae27c5ef5b390f9c090dd19e4fa76364c13/insightface-0.7.3.tar.gz (439 kB)
***   Installing build dependencies: started
***   Installing build dependencies: finished with status 'done'
***   Getting requirements to build wheel: started
***   Getting requirements to build wheel: finished with status 'done'
***   Installing backend dependencies: started
***   Installing backend dependencies: finished with status 'done'
***   Preparing metadata (pyproject.toml): started
***   Preparing metadata (pyproject.toml): finished with status 'done'
*** Requirement already satisfied: Pillow in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (9.5.0)
*** Requirement already satisfied: scikit-learn in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.4.1.post1)
*** Collecting easydict
***   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/05/ec/fa6963f1198172c2b75c9ab6ecefb3045991f92f75f5eb41b6621b198123/easydict-1.13-py3-none-any.whl (6.8 kB)
*** Requirement already satisfied: tqdm in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (4.66.2)
*** Collecting prettytable
***   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3d/c4/a32f4bf44faf95accbbd5d7864ddef9e289749a8efbc3adaad4a4671779a/prettytable-3.10.0-py3-none-any.whl (28 kB)
*** Requirement already satisfied: numpy in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.26.2)
*** Requirement already satisfied: scipy in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.12.0)
*** Collecting albumentations
***   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/95/78/046ba720532436716050c27fd71cb838d14a2dc4b676b7a0883e1e3deebe/albumentations-1.4.1-py3-none-any.whl (130 kB)
*** Collecting cython
***   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/47/82/135229b426f42c75e19a4ea1f0f63d046be1db709335e86cfaab768d680c/Cython-3.0.9-cp310-cp310-win_amd64.whl (2.8 MB)
*** Requirement already satisfied: scikit-image in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (0.21.0)
*** Requirement already satisfied: matplotlib in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (3.8.3)
*** Collecting onnx
***   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/1b/43/6e84bf35a9201fb344b1a98edf7095c4fa1cf1478dfb6638d7b77f5475e6/onnx-1.15.0-cp310-cp310-win_amd64.whl (14.3 MB)
*** Requirement already satisfied: requests in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (2.31.0)
*** Requirement already satisfied: typing-extensions>=4.9.0 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (4.10.0)
*** Collecting opencv-python-headless>=4.9.0
***   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/20/44/458a0a135866f5e08266566b32ad9a182a7a059a894effe6c41a9c841ff1/opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl (38.5 MB)   
*** Requirement already satisfied: PyYAML in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (6.0.1)
*** Requirement already satisfied: tifffile>=2022.8.12 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2024.2.12)
*** Requirement already satisfied: packaging>=21 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (24.0)
*** Requirement already satisfied: lazy_loader>=0.2 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (0.3)
*** Requirement already satisfied: PyWavelets>=1.1.1 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (1.5.0)
*** Requirement already satisfied: networkx>=2.8 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (3.2.1)
*** Requirement already satisfied: imageio>=2.27 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2.34.0)
*** Requirement already satisfied: threadpoolctl>=2.0.0 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from scikit-learn->insightface==0.7.3) (3.3.0)
*** Requirement already satisfied: joblib>=1.2.0 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from scikit-learn->insightface==0.7.3) (1.3.2)
*** Requirement already satisfied: pyparsing>=2.3.1 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (3.1.2)
*** Requirement already satisfied: fonttools>=4.22.0 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (4.49.0)
*** Requirement already satisfied: cycler>=0.10 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (0.12.1)
*** Requirement already satisfied: python-dateutil>=2.7 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (2.9.0.post0)
*** Requirement already satisfied: kiwisolver>=1.3.1 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.4.5)
*** Requirement already satisfied: contourpy>=1.0.1 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.2.0)
*** Collecting protobuf>=3.20.2
***   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ad/6e/1bed3b7c904cc178cb8ee8dbaf72934964452b3de95b7a63412591edb93c/protobuf-4.25.3-cp310-abi3-win_amd64.whl (413 kB)
*** Requirement already satisfied: wcwidth in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from prettytable->insightface==0.7.3) (0.2.13)
*** Requirement already satisfied: urllib3<3,>=1.21.1 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (2.0.7)
*** Requirement already satisfied: charset-normalizer<4,>=2 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.3.2)
*** Requirement already satisfied: certifi>=2017.4.17 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (2024.2.2)
*** Requirement already satisfied: idna<4,>=2.5 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.6)
*** Requirement already satisfied: colorama in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
*** Requirement already satisfied: six>=1.5 in f:\ai\sd\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
*** Building wheels for collected packages: insightface
***   Building wheel for insightface (pyproject.toml): started
***   Building wheel for insightface (pyproject.toml): finished with status 'error'
*** Failed to build insightface
***
*** stderr:   error: subprocess-exited-with-error
***
***   Building wheel for insightface (pyproject.toml) did not run successfully.
***   exit code: 1
***
***   [215 lines of output]
***   WARNING: pandoc not enabled
***   running bdist_wheel
***   running build
***   running build_py
***   creating build
***   creating build\lib.win-amd64-cpython-310
***   creating build\lib.win-amd64-cpython-310\insightface
***   copying insightface\__init__.py -> build\lib.win-amd64-cpython-310\insightface
***   creating build\lib.win-amd64-cpython-310\insightface\app
***   copying insightface\app\common.py -> build\lib.win-amd64-cpython-310\insightface\app
***   copying insightface\app\face_analysis.py -> build\lib.win-amd64-cpython-310\insightface\app
***   copying insightface\app\mask_renderer.py -> build\lib.win-amd64-cpython-310\insightface\app
***   copying insightface\app\__init__.py -> build\lib.win-amd64-cpython-310\insightface\app
***   creating build\lib.win-amd64-cpython-310\insightface\commands
***   copying insightface\commands\insightface_cli.py -> build\lib.win-amd64-cpython-310\insightface\commands
***   copying insightface\commands\model_download.py -> build\lib.win-amd64-cpython-310\insightface\commands
***   copying insightface\commands\rec_add_mask_param.py -> build\lib.win-amd64-cpython-310\insightface\commands
***   copying insightface\commands\__init__.py -> build\lib.win-amd64-cpython-310\insightface\commands
***   creating build\lib.win-amd64-cpython-310\insightface\data
***   copying insightface\data\image.py -> build\lib.win-amd64-cpython-310\insightface\data
***   copying insightface\data\pickle_object.py -> build\lib.win-amd64-cpython-310\insightface\data
***   copying insightface\data\rec_builder.py -> build\lib.win-amd64-cpython-310\insightface\data
***   copying insightface\data\__init__.py -> build\lib.win-amd64-cpython-310\insightface\data
***   creating build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\arcface_onnx.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\attribute.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\inswapper.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\landmark.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\model_store.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\model_zoo.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\retinaface.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\scrfd.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\__init__.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty
***   copying insightface\thirdparty\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty
***   creating build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\constant.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\download.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\face_align.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\filesystem.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\storage.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\transform.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\__init__.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d
***   copying insightface\thirdparty\face3d\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\io.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\light.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\render.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\transform.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\vis.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\io.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\light.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\render.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\transform.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\vis.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   copying insightface\thirdparty\face3d\morphable_model\fit.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   copying insightface\thirdparty\face3d\morphable_model\load.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   copying insightface\thirdparty\face3d\morphable_model\morphabel_model.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   copying insightface\thirdparty\face3d\morphable_model\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   running egg_info
***   writing insightface.egg-info\PKG-INFO
***   writing dependency_links to insightface.egg-info\dependency_links.txt
***   writing entry points to insightface.egg-info\entry_points.txt
***   writing requirements to insightface.egg-info\requires.txt
***   writing top-level names to insightface.egg-info\top_level.txt
***   reading manifest file 'insightface.egg-info\SOURCES.txt'
***   writing manifest file 'insightface.egg-info\SOURCES.txt'
***   C:\Users\Admin\AppData\Local\Temp\pip-build-env-4zg71gas\overlay\Lib\site-packages\setuptools\command\build_py.py:207: _Warning: Package 'insightface.thirdparty.face3d.mesh.cython' is absent 
from the `packages` configuration.
***   !!
***
***           ********************************************************************************
***           ############################
***           # Package would be ignored #
***           ############################
***           Python recognizes 'insightface.thirdparty.face3d.mesh.cython' as an importable package[^1],
***           but it is absent from setuptools' `packages` configuration.
***
***           This leads to an ambiguous overall configuration. If you want to distribute this
***           package, please make sure that 'insightface.thirdparty.face3d.mesh.cython' is explicitly added
***           to the `packages` configuration field.
***
***           Alternatively, you can also rely on setuptools' discovery methods
***           (for example by using `find_namespace_packages(...)`/`find_namespace:`
***           instead of `find_packages(...)`/`find:`).
***
***           You can read more about "package discovery" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
***
***           If you don't want 'insightface.thirdparty.face3d.mesh.cython' to be distributed and are
***           already explicitly excluding 'insightface.thirdparty.face3d.mesh.cython' via
***           `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
***           you can try to use `exclude_package_data`, or `include-package-data=False` in
***           combination with a more fine grained `package-data` configuration.
***
***           You can read more about "package data files" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
***
***
***           [^1]: For Python, any directory (with suitable naming) can be imported,
***                 even if it does not contain any `.py` files.
***                 On the other hand, currently there is no concept of package data
***                 directory, all directories are treated like packages.
***           ********************************************************************************
***
***   !!
***     check.warn(importable)
***   C:\Users\Admin\AppData\Local\Temp\pip-build-env-4zg71gas\overlay\Lib\site-packages\setuptools\command\build_py.py:207: _Warning: Package 'insightface.data.images' is absent from the `packages` configuration.
***   !!
***
***           ********************************************************************************
***           ############################
***           # Package would be ignored #
***           ############################
***           Python recognizes 'insightface.data.images' as an importable package[^1],
***           but it is absent from setuptools' `packages` configuration.
***
***           This leads to an ambiguous overall configuration. If you want to distribute this
***           package, please make sure that 'insightface.data.images' is explicitly added
***           to the `packages` configuration field.
***
***           Alternatively, you can also rely on setuptools' discovery methods
***           (for example by using `find_namespace_packages(...)`/`find_namespace:`
***           instead of `find_packages(...)`/`find:`).
***
***           You can read more about "package discovery" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
***
***           If you don't want 'insightface.data.images' to be distributed and are
***           already explicitly excluding 'insightface.data.images' via
***           `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
***           you can try to use `exclude_package_data`, or `include-package-data=False` in
***           combination with a more fine grained `package-data` configuration.
***
***           You can read more about "package data files" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
***
***
***           [^1]: For Python, any directory (with suitable naming) can be imported,
***                 even if it does not contain any `.py` files.
***                 On the other hand, currently there is no concept of package data
***                 directory, all directories are treated like packages.
***           ********************************************************************************
***
***   !!
***     check.warn(importable)
***   C:\Users\Admin\AppData\Local\Temp\pip-build-env-4zg71gas\overlay\Lib\site-packages\setuptools\command\build_py.py:207: _Warning: Package 'insightface.data.objects' is absent from the `packages` configuration.
***   !!
***
***           ********************************************************************************
***           ############################
***           # Package would be ignored #
***           ############################
***           Python recognizes 'insightface.data.objects' as an importable package[^1],
***           but it is absent from setuptools' `packages` configuration.
***
***           This leads to an ambiguous overall configuration. If you want to distribute this
***           package, please make sure that 'insightface.data.objects' is explicitly added
***           to the `packages` configuration field.
***
***           Alternatively, you can also rely on setuptools' discovery methods
***           (for example by using `find_namespace_packages(...)`/`find_namespace:`
***           instead of `find_packages(...)`/`find:`).
***
***           You can read more about "package discovery" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
***
***           If you don't want 'insightface.data.objects' to be distributed and are
***           already explicitly excluding 'insightface.data.objects' via
***           `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
***           you can try to use `exclude_package_data`, or `include-package-data=False` in
***           combination with a more fine grained `package-data` configuration.
***
***           You can read more about "package data files" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
***
***
***           [^1]: For Python, any directory (with suitable naming) can be imported,
***                 even if it does not contain any `.py` files.
***                 On the other hand, currently there is no concept of package data
***                 directory, all directories are treated like packages.
***           ********************************************************************************
***
***   !!
***     check.warn(importable)
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core.h -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   creating build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\Tom_Hanks_54745.png -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\mask_black.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\mask_blue.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\mask_green.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\mask_white.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\t1.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   creating build\lib.win-amd64-cpython-310\insightface\data\objects
***   copying insightface\data\objects\meanshape_68.pkl -> build\lib.win-amd64-cpython-310\insightface\data\objects
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.c -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.pyx -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\setup.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   running build_ext
***   building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
***   error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
***   [end of output]
***
***   note: This error originates from a subprocess, and is likely not a problem with pip.
***   ERROR: Failed building wheel for insightface
*** ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects
***
*** [notice] A new release of pip available: 22.2.1 -> 24.0
*** [notice] To update, run: F:\AI\SD\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
***
Launching Web UI with arguments: --no-download-sd-model --xformers --share --listen --enable-insecure-extension-access --skip-torch-cuda-test
F:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'F:\AI\SD\stable-diffusion-webui\venv\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can 
ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.2.1+cpu)
    Python  3.10.11 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
*** Error loading script: ui.py
    Traceback (most recent call last):
      File "F:\AI\SD\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\AI\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\AI\SD\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 8, in <module>
        from scripts.faceswap.swap import FaceSwap
      File "F:\AI\SD\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\faceswap\swap.py", line 6, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: wav2lip_uhq.py
    Traceback (most recent call last):
      File "F:\AI\SD\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\AI\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\AI\SD\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 11, in <module>
        init_wav2lip_uhq()
      File "F:\AI\SD\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 7, in init_wav2lip_uhq
        from ui import on_ui_tabs
      File "F:\AI\SD\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 8, in <module>
        from scripts.faceswap.swap import FaceSwap
      File "F:\AI\SD\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\faceswap\swap.py", line 6, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
Loading weights [6ce0161689] from F:\AI\SD\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: F:\AI\SD\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://0.0.0.0:7860
Applying attention optimization: InvokeAI... done.
loading stable diffusion model: AssertionError
Traceback (most recent call last):
  File "F:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "F:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "F:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "F:\AI\SD\stable-diffusion-webui\modules\initialize.py", line 148, in load_model
    shared.sd_model  # noqa: B018
  File "F:\AI\SD\stable-diffusion-webui\modules\shared_items.py", line 133, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "F:\AI\SD\stable-diffusion-webui\modules\sd_models.py", line 621, in get_sd_model
    load_model()
  File "F:\AI\SD\stable-diffusion-webui\modules\sd_models.py", line 771, in load_model
    with devices.autocast(), torch.no_grad():
  File "F:\AI\SD\stable-diffusion-webui\modules\devices.py", line 218, in autocast
    if has_xpu() or has_mps() or cuda_no_autocast():
  File "F:\AI\SD\stable-diffusion-webui\modules\devices.py", line 28, in cuda_no_autocast
    device_id = get_cuda_device_id()
  File "F:\AI\SD\stable-diffusion-webui\modules\devices.py", line 40, in get_cuda_device_id
    ) or torch.cuda.current_device()
  File "F:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
    _lazy_init()
  File "F:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Stable diffusion model failed to load
Running on public URL: https://b95fb6996b080ea35e.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Startup time: 63.8s (prepare environment: 41.4s, import torch: 5.6s, import gradio: 1.3s, setup paths: 1.1s, initialize shared: 0.2s, other imports: 0.7s, load scripts: 1.5s, create ui: 0.4s, gradio launch: 11.6s).

**Comment by hotdogarea** [comment]
![image](https://github.com/numz/sd-wav2lip-uhq/assets/11146882/0bc8478c-70b5-48dd-a9b4-49d156c34b67)

**Comment by hotdogarea** [comment]
![image](https://github.com/numz/sd-wav2lip-uhq/assets/11146882/f5452109-dff5-4663-abe7-0338be246cd0)

**Comment by hotdogarea** [comment]
![image](https://github.com/numz/sd-wav2lip-uhq/assets/11146882/3d091904-e8a4-4dea-8503-64f757b41abc)

**Comment by hotdogarea** [comment]
![image](https://github.com/numz/sd-wav2lip-uhq/assets/11146882/9ad065e9-ad52-4937-9177-106fd4323a2b)
重新卸载显卡驱动 去下载适配当前torchversion的版本，这个可以从https://pytorch.org/get-started/previous-versions/ 找到
可以解决torch报错的问题，当前程序适配的N卡cuda最大值不超过12.1
