### ISSUE TITLE
Automatic1111 Ext not work

### ISSUE THREAD

**Issue by hoanghohotel** [numz/sd-wav2lip-uhq#114]
Hi
I'm try install via automatic1111
Download all file from Note 6

`Important: Get the weights. Download the model weights from the following locations and place them in the corresponding directories (take care about the filename, especially for s3fd)`
Have same file shape_predictor_68_face_landmarks.dat so need 1 only?
After restart UI automatic1111
Show error

`*** Error loading script: wav2lip_uhq.py
    Traceback (most recent call last):
      File "G:\sd.webui\webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 11, in <module>
        init_wav2lip_uhq()
      File "G:\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 7, in init_wav2lip_uhq
        from ui import on_ui_tabs
      File "G:\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 7, in <module>
        from scripts.bark.tts import TTS
      File "G:\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\bark\tts.py", line 5, in <module>
        from bark.generation import (
    ModuleNotFoundError: No module named 'bark.generation'`

I'm try install
pip install git+https://github.com/suno-ai/bark.git
and
choco install ffmpeg-full

But not working

**Comment by nitinmukesh** [comment]
Not only it doesn't work, it crashes Automatic1111.

**Comment by DavidSchobl** [comment]
It not only crashes automatic, it wrecks completely the installation,

**Comment by VitaliyAT** [comment]
A few moments before I got this meassage too, but I delete extention folder and reinstall extention, but in this time I wait as much as needed and do not tuch any buttons in.... Forge. Yes it was in Forge - not in 1111, and I don't see any errors after, but still don't understand where it should be finded. I try run it first time.
