### ISSUE TITLE
SD菜单栏没有显示wave2lip 

### ISSUE THREAD

**Issue by ZYOhub** [numz/sd-wav2lip-uhq#128]

**Comment by ZYOhub** [comment]
在我安装好插件，配置好文件之后 SD的菜单栏并没有显示wav2lip
以下是我的启动日志
[Diagnostics-1719368002.log](https://github.com/user-attachments/files/15981494/Diagnostics-1719368002.log)

和启动中运行代码
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.9.3
Commit hash: 1c0a0c4c26f78c32095ebc7f8af82f5c04fca8c0
Installing wav2lip_uhq requirement: librosa==0.10.0.post2
Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git
Installing wav2lip_uhq requirement: insightface==0.7.3
Installing wav2lip_uhq requirement: onnx==1.14.0
Installing wav2lip_uhq requirement: onnxruntime==1.15.0
Installing wav2lip_uhq requirement: onnxruntime-gpu==1.15.0
Installing wav2lip_uhq requirement: opencv-python>=4.8.0
CUDA 11.8
Looking in indexes: https://pypi.doubanio.com/simple
Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html, https://pypi.oystermercury.top/
Requirement already satisfied: onnxruntime-gpu in d:\soft\stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages (1.15.0)
Collecting onnxruntime-gpu
  Using cached https://mirrors.cloud.tencent.com/pypi/packages/e4/b4/b31ad597ee61b0a08c3a84930d96d6c53a39f19e12db3c8a09e6297bf478/onnxruntime_gpu-1.18.0-cp310-cp310-win_amd64.whl (157.7 MB)
Requirement already satisfied: coloredlogs in d:\soft\stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages (from onnxruntime-gpu) (15.0.1)
Requirement already satisfied: flatbuffers in d:\soft\stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages (from onnxruntime-gpu) (23.3.3)
Requirement already satisfied: numpy>=1.21.6 in d:\soft\stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages (from onnxruntime-gpu) (1.26.2)
Requirement already satisfied: packaging in d:\soft\stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages (from onnxruntime-gpu) (23.1)
Requirement already satisfied: protobuf in d:\soft\stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages (from onnxruntime-gpu) (3.20.3)
Requirement already satisfied: sympy in d:\soft\stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages (from onnxruntime-gpu) (1.11.1)
Requirement already satisfied: humanfriendly>=9.1 in d:\soft\stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages (from coloredlogs->onnxruntime-gpu) (10.0)
Requirement already satisfied: mpmath>=0.19 in d:\soft\stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages (from sympy->onnxruntime-gpu) (1.3.0)
Requirement already satisfied: pyreadline3 in d:\soft\stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime-gpu) (3.4.1)
Installing collected packages: onnxruntime-gpu
  Attempting uninstall: onnxruntime-gpu
    Found existing installation: onnxruntime-gpu 1.15.0
    Uninstalling onnxruntime-gpu-1.15.0:
      Successfully uninstalled onnxruntime-gpu-1.15.0
Successfully installed onnxruntime-gpu-1.18.0

        +---------------------------------+
        --- PLEASE, RESTART the Server! ---
        +---------------------------------+
Launching Web UI with arguments: --theme dark --xformers --xformers-flash-attention --api --autolaunch
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer: Failed to load model 'yolov8x-worldv2.pt' from huggingface
[-] ADetailer initialized. version: 24.6.0, num models: 9
Downloading the detection model to C:\Users\Secretlisa\.ifnude/detector.onnx
*** Error loading script: ui.py
    Traceback (most recent call last):
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\http\client.py", line 1283, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\http\client.py", line 1329, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\http\client.py", line 1278, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\http\client.py", line 1038, in _send_output
        self.send(msg)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\http\client.py", line 976, in send
        self.connect()
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\http\client.py", line 1455, in connect
        self.sock = self._context.wrap_socket(self.sock,
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\ssl.py", line 513, in wrap_socket
        return self.sslsocket_class._create(
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\ssl.py", line 1071, in _create
        self.do_handshake()
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\ssl.py", line 1342, in do_handshake
        self._sslobj.do_handshake()
    FileNotFoundError: [Errno 2] No such file or directory

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\extensions\sd-wav2lip-uhq\scripts\ui.py", line 8, in <module>
        from scripts.faceswap.swap import FaceSwap
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\extensions\sd-wav2lip-uhq\scripts\faceswap\swap.py", line 16, in <module>
        from ifnude import detect
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages\ifnude\__init__.py", line 1, in <module>
        from .detector import detect
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages\ifnude\detector.py", line 36, in <module>
        download(model_url, model_path)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages\ifnude\detector.py", line 16, in download
        request = urllib.request.urlopen(url)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 519, in open
        response = self._open(req, data)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 496, in _call_chain
        result = func(*args)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 1351, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

---
Downloading the detection model to C:\Users\Secretlisa\.ifnude/detector.onnx
*** Error loading script: wav2lip_uhq.py
    Traceback (most recent call last):
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\http\client.py", line 1283, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\http\client.py", line 1329, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\http\client.py", line 1278, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\http\client.py", line 1038, in _send_output
        self.send(msg)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\http\client.py", line 976, in send
        self.connect()
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\http\client.py", line 1455, in connect
        self.sock = self._context.wrap_socket(self.sock,
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\ssl.py", line 513, in wrap_socket
        return self.sslsocket_class._create(
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\ssl.py", line 1071, in _create
        self.do_handshake()
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\ssl.py", line 1342, in do_handshake
        self._sslobj.do_handshake()
    FileNotFoundError: [Errno 2] No such file or directory

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 11, in <module>
        init_wav2lip_uhq()
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 7, in init_wav2lip_uhq
        from ui import on_ui_tabs
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\extensions\sd-wav2lip-uhq\scripts\ui.py", line 8, in <module>
        from scripts.faceswap.swap import FaceSwap
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\extensions\sd-wav2lip-uhq\scripts\faceswap\swap.py", line 16, in <module>
        from ifnude import detect
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages\ifnude\__init__.py", line 1, in <module>
        from .detector import detect
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages\ifnude\detector.py", line 36, in <module>
        download(model_url, model_path)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\site-packages\ifnude\detector.py", line 16, in download
        request = urllib.request.urlopen(url)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 519, in open
        response = self._open(req, data)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 496, in _call_chain
        result = func(*args)
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "D:\Soft\Stable diffusion\sd-webui-aki-v4.7\python\lib\urllib\request.py", line 1351, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

---
ControlNet preprocessor location: D:\Soft\Stable diffusion\sd-webui-aki-v4.7\extensions\sd-webui-controlnet\annotator\downloads
2024-06-26 10:10:03,015 - ControlNet - INFO - ControlNet v1.1.449
sd-webui-prompt-all-in-one background API service started successfully.
10:10:03 - ReActor - STATUS - Running v0.7.0-b7 on Device: CUDA
Loading weights [e44c7b30c6] from D:\Soft\Stable diffusion\sd-webui-aki-v4.7\models\Stable-diffusion\epicphotogasm_ultimateFidelity.safetensors
Creating model from config: D:\Soft\Stable diffusion\sd-webui-aki-v4.7\configs\v1-inference.yaml
2024-06-26 10:10:04,288 - ControlNet - INFO - ControlNet UI callback registered.
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
IIB Database file has been successfully backed up to the backup folder.
Startup time: 130.6s (prepare environment: 100.3s, import torch: 4.0s, import gradio: 1.0s, setup paths: 0.6s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 21.8s, create ui: 0.8s, gradio launch: 0.5s, add APIs: 0.5s, app_started_callback: 0.3s).
Applying attention optimization: xformers... done.

**Comment by gilushon** [comment]
Yes, for me too it doesn't show the menu bar of wav2lip after installation, please help us with a solution, thank you!
