### ISSUE TITLE
Unexpected version found while deserializing dlib::shape_predictor

### ISSUE THREAD

**Issue by Lesteriax** [numz/sd-wav2lip-uhq#13]
Any way to get around his error?

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/ui.py", line 46, in generate
    w2luhq.execute()
  File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/wav2lip_uhq.py", line 173, in execute
    detector, predictor = self.initialize_dlib_predictor()
  File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/wav2lip_uhq.py", line 146, in initialize_dlib_predictor
    predictor = dlib.shape_predictor(self.wav2lip_folder + "/predicator/shape_predictor_68_face_landmarks.dat")
RuntimeError: Unexpected version found while deserializing dlib::shape_predictor.

**Comment by T3-sudo** [comment]
Hey Numz. First off thanks for compiling this for A1111. Lesteriax its most likely the broken shape_predictor_68_face_landmarks.dat in the first link. Just dl from one of  the subsequent links listed and it should work. I had the same issue but then checked the size of the model and seemed too small.

**Comment by numz** [comment]
Hi

Thank you  @T3-sudo!! Really appreciate 😀
I'll correct it later

@Lesteriax ,is that resolve the problem ?

Thank you guys!

**Comment by Lesteriax** [comment]
Thank you @T3-sudo, that did the trick.

@numz, yes I'm currently using it with no issues. Seems the first link has an issue or it might be an issue from my end while downloading it.

**Comment by numz** [comment]
Ok, cool.  Thank you :)
I close this issue
