### ISSUE TITLE
cant reload after installed extension

### ISSUE THREAD

**Issue by vutatthanh1702** [numz/sd-wav2lip-uhq#30]
/test/SDXL/stable-diffusion-webui$ ./webui.sh --listen

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on aiteam user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc_minimal.so.4
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Version: v1.5.2
Commit hash: c9c8485bc1e8720aba70f029d25cba1c4abf2b5c
Installing wav2lip_uhq requirement: dlib-bin
Installing wav2lip_uhq requirement: opencv-python
Installing wav2lip_uhq requirement: pillow
Installing wav2lip_uhq requirement: librosa==0.10.0.post2
Installing wav2lip_uhq requirement: opencv-contrib-python
Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git

Launching Web UI with arguments: --listen
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
./webui.sh: line 254:  1963 Illegal instruction     (core dumped) "${python_cmd}" "${LAUNCH_SCRIPT}" "$@"

**Comment by vutatthanh1702** [comment]
the above error is when I run use CUDA 117
this bellow error is when I run use cuda 118
Installing wav2lip_uhq requirement: librosa==0.10.0.post2
Installing wav2lip_uhq requirement: opencv-contrib-python
Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git

Launching Web UI with arguments: --listen --enable-insecure-extension-access
Traceback (most recent call last):
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/launch.py", line 39, in <module>
    main()
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/launch.py", line 35, in main
    start()
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/modules/launch_utils.py", line 390, in start
    import webui
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/webui.py", line 39, in <module>
    import pytorch_lightning   # noqa: F401 # pytorch_lightning should be imported after torch, but it re-enables warnings on import so import once to disable them
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/pytorch_lightning/utilities/types.py", line 27, in <module>
    from torchmetrics import Metric
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/utilities/data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/utilities/imports.py", line 50, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/lightning_utilities/core/imports.py", line 73, in compare_version
    pkg = importlib.import_module(package)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 47, in <module>
    _check_cuda_version()
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 119, in _check_cuda_version
    raise RuntimeError(
RuntimeError: Detected that PyTorch and TorchAudio were compiled with different CUDA versions. PyTorch has CUDA version 11.8 whereas TorchAudio has CUDA version 11.7. Please install the TorchAudio version that matches your PyTorch version.

**Comment by numz** [comment]
Hi,
sorry about that, 
Just for check, can you install torchaudio with cuda 11.8?

in your env just type : 
pip uninstall torchaudio
pip install torchaudio --index-url https://download.pytorch.org/whl/cu118

let me know :)

**Comment by vutatthanh1702** [comment]
I did that but still error
aiteam@test:~/test/SDXL/stable-diffusion-webui$ ./webui.sh --listen --enable-insecure-extension-access

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on aiteam user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc_minimal.so.4
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Version: v1.5.2
Commit hash: c9c8485bc1e8720aba70f029d25cba1c4abf2b5c
Launching Web UI with arguments: --listen --enable-insecure-extension-access
Traceback (most recent call last):
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/launch.py", line 39, in <module>
    main()
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/launch.py", line 35, in main
    start()
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/modules/launch_utils.py", line 390, in start
    import webui
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/webui.py", line 39, in <module>
    import pytorch_lightning   # noqa: F401 # pytorch_lightning should be imported after torch, but it re-enables warnings on import so import once to disable them
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/pytorch_lightning/utilities/types.py", line 27, in <module>
    from torchmetrics import Metric
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/utilities/data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchmetrics/utilities/imports.py", line 50, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/lightning_utilities/core/imports.py", line 73, in compare_version
    pkg = importlib.import_module(package)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 47, in <module>
    _check_cuda_version()
  File "/home/aiteam/test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 119, in _check_cuda_version
    raise RuntimeError(
RuntimeError: Detected that PyTorch and TorchAudio were compiled with different CUDA versions. PyTorch has CUDA version 11.8 whereas TorchAudio has CUDA version 11.7. Please install the TorchAudio version that matches your PyTorch version.
aiteam@test:~/test/SDXL/stable-diffusion-webui$ python3 -c "import torchaudio; print(torchaudio.__version__)"
2.0.2+cu118

**Comment by numz** [comment]
ok thanks, 
It seems that the torchaudio installed wasn't done in venv of automatic1111
did you load venv before launch pip install?

**Comment by vutatthanh1702** [comment]
I installed  but after that it showed difference error, same error  when I use CUDA 117
`(venv) aiteam@test:~$ pip install torchaudio --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torchaudio
  Using cached https://download.pytorch.org/whl/cu118/torchaudio-2.0.2%2Bcu118-cp310-cp310-linux_x86_64.whl (4.4 MB)
Requirement already satisfied: torch==2.0.1 in ./test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages (from torchaudio) (2.0.1+cu118)
Requirement already satisfied: jinja2 in ./test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages (from torch==2.0.1->torchaudio) (3.1.2)
Requirement already satisfied: triton==2.0.0 in ./test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages (from torch==2.0.1->torchaudio) (2.0.0)
Requirement already satisfied: filelock in ./test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages (from torch==2.0.1->torchaudio) (3.12.2)
Requirement already satisfied: sympy in ./test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages (from torch==2.0.1->torchaudio) (1.12)
Requirement already satisfied: typing-extensions in ./test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages (from torch==2.0.1->torchaudio) (4.7.1)
Requirement already satisfied: networkx in ./test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages (from torch==2.0.1->torchaudio) (3.1)
Requirement already satisfied: lit in ./test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages (from triton==2.0.0->torch==2.0.1->torchaudio) (16.0.6)
Requirement already satisfied: cmake in ./test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages (from triton==2.0.0->torch==2.0.1->torchaudio) (3.27.4)
Requirement already satisfied: MarkupSafe>=2.0 in ./test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages (from jinja2->torch==2.0.1->torchaudio) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in ./test/SDXL/stable-diffusion-webui/venv/lib/python3.10/site-packages (from sympy->torch==2.0.1->torchaudio) (1.3.0)
Installing collected packages: torchaudio
Successfully installed torchaudio-2.0.2+cu118`

`(venv) aiteam@test:~/test/SDXL/stable-diffusion-webui$ ./webui.sh --listen --enable-insecure-extension-access

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on aiteam user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
python venv already activate or run without venv: /home/aiteam/test/SDXL/stable-diffusion-webui/venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc_minimal.so.4
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Version: v1.5.2
Commit hash: c9c8485bc1e8720aba70f029d25cba1c4abf2b5c
Installing wav2lip_uhq requirement: dlib-bin
Installing wav2lip_uhq requirement: opencv-python
Installing wav2lip_uhq requirement: pillow
Installing wav2lip_uhq requirement: librosa==0.10.0.post2
Installing wav2lip_uhq requirement: opencv-contrib-python
Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git

Launching Web UI with arguments: --listen --enable-insecure-extension-access
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
./webui.sh: line 254:  1957 Illegal instruction     (core dumped) "${python_cmd}" "${LAUNCH_SCRIPT}" "$@"`

**Comment by vutatthanh1702** [comment]
aiteam@test:~/test/SDXL/stable-diffusion-webui$ cat /proc/cpuinfo | grep flags | tail -1
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid pni ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes hypervisor lahf_lm cpuid_fault pti
aiteam@test:~/test/SDXL/stable-diffusion-webui$ lscpu
Architecture:           x86_64
  CPU op-mode(s):       32-bit, 64-bit
  Address sizes:        40 bits physical, 48 bits virtual
  Byte Order:           Little Endian
CPU(s):                 16
  On-line CPU(s) list:  0-15
Vendor ID:              GenuineIntel
  Model name:           QEMU Virtual CPU version 2.5+
    CPU family:         15
    Model:              107
    Thread(s) per core: 1
    Core(s) per socket: 16
    Socket(s):          1
    Stepping:           1
    BogoMIPS:           4599.95
    Flags:              fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid pni ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes hyperv
                        isor lahf_lm cpuid_fault pti
Caches (sum of all):    
  L1d:                  512 KiB (16 instances)
  L1i:                  512 KiB (16 instances)
  L2:                   64 MiB (16 instances)
  L3:                   16 MiB (1 instance)
NUMA:                   
  NUMA node(s):         1
  NUMA node0 CPU(s):    0-15
Vulnerabilities:        
  Itlb multihit:        KVM: Mitigation: VMX unsupported
  L1tf:                 Mitigation; PTE Inversion
  Mds:                  Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
  Meltdown:             Mitigation; PTI
  Mmio stale data:      Unknown: No mitigations
  Retbleed:             Not affected
  Spec store bypass:    Vulnerable
  Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:           Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                Not affected
  Tsx async abort:      Not affected

**Comment by vutatthanh1702** [comment]
OK it worked, Im using vm in promox, but chose cpu wrong, need to use ''host''
