### ISSUE TITLE
Everytime I run I get this error:RuntimeError: unexpected EOF, expected 9218993 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by Hemajun2018** [numz/sd-wav2lip-uhq#31]
Using cuda for inference.
Reading video frames...
Number of frames available for inference: 114
(80, 1335)
Length of mel chunks: 496
  0% 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/ui.py", line 154, in generate
    w2l.execute()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/w2l.py", line 250, in execute
    for i, (img_batch, mel_batch, frames, coords) in enumerate(tqdm(gen,
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/w2l.py", line 114, in datagen
    face_det_results = self.face_detect(frames)  # BGR2RGB for CNN face detection
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/w2l.py", line 65, in face_detect
    detector = face_detection.FaceAlignment(face_detection.LandmarksType._2D,
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/face_detection/api.py", line 59, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/face_detection/detection/sfd/sfd_detector.py", line 24, in __init__
    model_weights = torch.load(path_to_detector)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 108, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 156, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 9218993 more bytes. The file might be corrupted.

**Comment by numz** [comment]
Hi, sorry about that,

It seems there is an error with the s3fd.pth model
perhaps try to download it again, and let me know

regards

**Comment by numz** [comment]
It seems this error come when you don't downloads models or putted in wrong folder or you don"t rename s3fd.pth file.

Let me know :)
Regards

**Comment by numz** [comment]
Seems to be related to non download models
