### ISSUE TITLE
安装不上什么情况，大佬说说

### ISSUE THREAD

**Issue by corepro** [numz/sd-wav2lip-uhq#42]
*** Error loading script: wav2lip_uhq.py
    Traceback (most recent call last):
      File "D:\sd\sd-webui-aki-v4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\sd\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\sd\sd-webui-aki-v4\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 11, in <module>
        init_wav2lip_uhq()
      File "D:\sd\sd-webui-aki-v4\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 7, in init_wav2lip_uhq
        from ui import on_ui_tabs
      File "D:\sd\sd-webui-aki-v4\extensions\sd-wav2lip-uhq\scripts\ui.py", line 7, in <module>
        from scripts.bark.tts import TTS
      File "D:\sd\sd-webui-aki-v4\extensions\sd-wav2lip-uhq\scripts\bark\tts.py", line 5, in <module>
        from bark.generation import (
    ModuleNotFoundError: No module named 'bark.generation'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by numz** [comment]
bark安装失败，请问你的python版本是多少？

**Comment by vantang** [comment]
你需要梯子

> *** Error loading script: wav2lip_uhq.py Traceback (most recent call last): File "D:\sd\sd-webui-aki-v4\modules\scripts.py", line 382, in load_scripts script_module = script_loading.load_module(scriptfile.path) File "D:\sd\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module module_spec.loader.exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "D:\sd\sd-webui-aki-v4\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 11, in init_wav2lip_uhq() File "D:\sd\sd-webui-aki-v4\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 7, in init_wav2lip_uhq from ui import on_ui_tabs File "D:\sd\sd-webui-aki-v4\extensions\sd-wav2lip-uhq\scripts\ui.py", line 7, in from scripts.bark.tts import TTS File "D:\sd\sd-webui-aki-v4\extensions\sd-wav2lip-uhq\scripts\bark\tts.py", line 5, in from bark.generation import ( ModuleNotFoundError: No module named 'bark.generation' 提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
