### ISSUE TITLE
Getting this error on M1

### ISSUE THREAD

**Issue by Itchy-Fingaz** [numz/sd-wav2lip-uhq#55]
*** Error loading script: wav2lip_uhq.py
    Traceback (most recent call last):
      File "/Users/chief/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/chief/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/chief/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip_uhq.py", line 11, in <module>
        init_wav2lip_uhq()
      File "/Users/chief/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip_uhq.py", line 7, in init_wav2lip_uhq
        from ui import on_ui_tabs
      File "/Users/chief/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/ui.py", line 5, in <module>
        from scripts.wav2lip.wav2lip_uhq import Wav2LipUHQ
      File "/Users/chief/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/wav2lip_uhq.py", line 4, in <module>
        import dlib
      File "/Users/chief/stable-diffusion-webui/venv/lib/python3.10/site-packages/dlib/__init__.py", line 19, in <module>
        from _dlib_pybind11 import *
    ImportError: dlopen(/Users/chief/stable-diffusion-webui/venv/lib/python3.10/site-packages/_dlib_pybind11.cpython-310-darwin.so, 0x0002): Library not loaded: '/opt/homebrew/opt/ffmpeg/lib/libavdevice.59.dylib'
      Referenced from: '/Users/chief/stable-diffusion-webui/venv/lib/python3.10/site-packages/_dlib_pybind11.cpython-310-darwin.so'
      Reason: tried: '/opt/homebrew/opt/ffmpeg/lib/libavdevice.59.dylib' (no such file), '/usr/local/lib/libavdevice.59.dylib' (no such file), '/usr/lib/libavdevice.59.dylib' (no such file), '/opt/homebrew/Cellar/ffmpeg/6.0_1/lib/libavdevice.59.dylib' (no such file), '/usr/local/lib/libavdevice.59.dylib' (no such file), '/usr/lib/libavdevice.59.dylib' (no such file)

**Comment by numz** [comment]
Hi,
Did you install ffmpeg?

**Comment by Itchy-Fingaz** [comment]
yes ffmpeg is installed. I reinstalled twice. Also dlib. reinstalled twice. please help me out!

**Comment by Itchy-Fingaz** [comment]
ffpmeg --version gives this


ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
built with Apple clang version 14.0.0 (clang-1400.0.29.202)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.0_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100

**Comment by Itchy-Fingaz** [comment]
just just as experiment I copied the libavdevice60 file to libavdevice59 

now I get this error

*** Error loading script: wav2lip_uhq.py
    Traceback (most recent call last):
      File "/Users/chief/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/chief/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/chief/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip_uhq.py", line 11, in <module>
        init_wav2lip_uhq()
      File "/Users/chief/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip_uhq.py", line 7, in init_wav2lip_uhq
        from ui import on_ui_tabs
      File "/Users/chief/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/ui.py", line 5, in <module>
        from scripts.wav2lip.wav2lip_uhq import Wav2LipUHQ
      File "/Users/chief/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/wav2lip_uhq.py", line 4, in <module>
        import dlib
      File "/Users/chief/stable-diffusion-webui/venv/lib/python3.10/site-packages/dlib/__init__.py", line 19, in <module>
        from _dlib_pybind11 import *
    ImportError: dlopen(/Users/chief/stable-diffusion-webui/venv/lib/python3.10/site-packages/_dlib_pybind11.cpython-310-darwin.so, 0x0002): Library not loaded: '/opt/homebrew/opt/ffmpeg/lib/libavfilter.8.dylib'
      Referenced from: '/Users/chief/stable-diffusion-webui/venv/lib/python3.10/site-packages/_dlib_pybind11.cpython-310-darwin.so'
      Reason: tried: '/opt/homebrew/opt/ffmpeg/lib/libavfilter.8.dylib' (no such file), '/usr/local/lib/libavfilter.8.dylib' (no such file), '/usr/lib/libavfilter.8.dylib' (no such file), '/opt/homebrew/Cellar/ffmpeg/6.0_1/lib/libavfilter.8.dylib' (no such file), '/usr/local/lib/libavfilter.8.dylib' (no such file), '/usr/lib/libavfilter.8.dylib' (no such file)

**Comment by Itchy-Fingaz** [comment]
seems to me it's a ffmpeg version issue but I don't have the knowhow to fix this yet.

**Comment by vantang** [comment]
how did you reach this issue? generating video? or starting webUI?

**Comment by vantang** [comment]
it works well in my M2.
here is my ffmpeg version information for your inference

ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.0_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**Comment by cantonalex** [comment]
@Itchy-Fingaz did you fix this?
