### ISSUE TITLE
unable to install, previous versions were fine.

### ISSUE THREAD

**Issue by trxsudo** [numz/sd-wav2lip-uhq#56]
*** Error running install.py for extension D:\sdai\sd-webui-aki-v4.2\extensions\sd-wav2lip-uhq.
*** Command: "D:\sdai\sd-webui-aki-v4.2\python\python.exe" "D:\sdai\sd-webui-aki-v4.2\extensions\sd-wav2lip-uhq\install.py"
*** Error code: 1
*** stdout: Installing wav2lip_uhq requirement: dlib-bin
*** Installing wav2lip_uhq requirement: opencv-python
*** Installing wav2lip_uhq requirement: pillow
*** Installing wav2lip_uhq requirement: librosa==0.10.0.post2
*** Installing wav2lip_uhq requirement: opencv-contrib-python
*** Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git
*** Installing wav2lip_uhq requirement: insightface==0.7.3
*** 
*** stderr: Traceback (most recent call last):
***   File "D:\sdai\sd-webui-aki-v4.2\extensions\sd-wav2lip-uhq\install.py", line 17, in <module>
***     launch.run_pip(f"install {lib}", f"wav2lip_uhq requirement: {lib}")
***   File "D:\sdai\sd-webui-aki-v4.2\.launcher\pyinterop.hfkx1kkk0g4q7.zip\swlpatches\progress\launch.py", line 49, in wrapped_run_pip
***   File "D:\sdai\sd-webui-aki-v4.2\modules\launch_utils.py", line 136, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "D:\sdai\sd-webui-aki-v4.2\modules\launch_utils.py", line 113, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install wav2lip_uhq requirement: insightface==0.7.3.
*** Command: "D:\sdai\sd-webui-aki-v4.2\python\python.exe" -m pip install insightface==0.7.3 --prefer-binary
*** Error code: 1
*** stdout: Looking in indexes: https://mirrors.cloud.tencent.com/pypi/simple
*** Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html
*** Collecting insightface==0.7.3
***   Downloading https://mirrors.cloud.tencent.com/pypi/packages/0b/8d/0f4af90999ca96cf8cb846eb5ae27c5ef5b390f9c090dd19e4fa76364c13/insightface-0.7.3.tar.gz (439 kB)
***   Installing build dependencies: started
***   Installing build dependencies: finished with status 'error'
*** 
*** stderr:   error: subprocess-exited-with-error
***   
***   × pip subprocess to install build dependencies did not run successfully.
***   │ exit code: 2
***   ╰─> [87 lines of output]
***       Looking in indexes: https://mirrors.cloud.tencent.com/pypi/simple
***       Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html, https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html
***       Collecting setuptools
***         Using cached https://mirrors.cloud.tencent.com/pypi/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl (807 kB)
***       Collecting numpy
***         Downloading https://mirrors.cloud.tencent.com/pypi/packages/cc/05/ef9fc04adda45d537619ea956bc33489f50a46badc949c4280d8309185ec/numpy-1.26.0-cp310-cp310-win_amd64.whl (15.8 MB)
***       WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='mirror.sjtu.edu.cn', port=443): Read timed out. (read timeout=8.0)")': /pytorch-wheels/torch_stable.html
***       Collecting cython
***         Downloading https://mirrors.cloud.tencent.com/pypi/packages/db/3e/8cf60af86446b129e79adee5d9131ec7eb043297e20c04bc31670331325c/Cython-3.0.2-cp310-cp310-win_amd64.whl (2.8 MB)
***       ERROR: Exception:
***       Traceback (most recent call last):
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
***           yield
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
***           data = self._fp_read(amt) if not fp_closed else b""
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
***           return self._fp.read(amt) if amt is not None else self._fp.read()
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
***           data = self.__fp.read(amt)
***         File "D:\sdai\sd-webui-aki-v4.2\python\lib\http\client.py", line 466, in read
***           s = self.fp.read(amt)
***         File "D:\sdai\sd-webui-aki-v4.2\python\lib\socket.py", line 705, in readinto
***           return self._sock.recv_into(b)
***         File "D:\sdai\sd-webui-aki-v4.2\python\lib\ssl.py", line 1274, in recv_into
***           return self.read(nbytes, buffer)
***         File "D:\sdai\sd-webui-aki-v4.2\python\lib\ssl.py", line 1130, in read
***           return self._sslobj.read(len, buffer)
***       TimeoutError: The read operation timed out
***       
***       During handling of the above exception, another exception occurred:
***       
***       Traceback (most recent call last):
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
***           status = run_func(*args)
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
***           return func(self, options, args)
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
***           requirement_set = resolver.resolve(
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
***           result = self._result = resolver.resolve(
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
***           state = resolution.resolve(requirements, max_rounds=max_rounds)
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
***           self._add_to_criteria(self.state.criteria, r, parent=None)
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
***           if not criterion.candidates:
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
***           return bool(self._sequence)
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
***           return any(self)
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
***           return (c for c in iterator if id(c) not in self._incompatible_ids)
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
***           candidate = func()
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
***           self._link_candidate_cache[link] = LinkCandidate(
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
***           super().__init__(
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
***           self.dist = self._prepare()
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
***           dist = self._prepare_distribution()
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
***           return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\operations\prepare.py", line 516, in prepare_linked_requirement
***           return self._prepare_linked_requirement(req, parallel_builds)
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\operations\prepare.py", line 587, in _prepare_linked_requirement
***           local_file = unpack_url(
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\operations\prepare.py", line 166, in unpack_url
***           file = get_http_url(
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url
***           from_path, content_type = download(link, temp_dir.path)
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
***           for chunk in chunks:
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
***           for chunk in iterable:
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
***           for chunk in response.raw.stream(
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
***           data = self.read(amt=amt, decode_content=decode_content)
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
***           with self._error_catcher():
***         File "D:\sdai\sd-webui-aki-v4.2\python\lib\contextlib.py", line 153, in __exit__
***           self.gen.throw(typ, value, traceback)
***         File "D:\sdai\sd-webui-aki-v4.2\python\Lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
***           raise ReadTimeoutError(self._pool, None, "Read timed out.")
***       pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='mirrors.cloud.tencent.com', port=443): Read timed out.
***       [end of output]
***   
***   note: This error originates from a subprocess, and is likely not a problem with pip.
*** error: subprocess-exited-with-error
*** 
*** × pip subprocess to install build dependencies did not run successfully.
*** │ exit code: 2
*** ╰─> See above for output.
*** 
*** note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by trxsudo** [comment]
> Try to set face erode to something like 40 ,mask blur to 30 and use gfpgan, Let me know

just your suggested parameters, and the result is kind of off, here is the video:
where the teeth seems crooked and too crowded. not sure if it is because the mask isnt covering the teeth in the original video
https://github.com/numz/sd-wav2lip-uhq/assets/76946041/0a87d151-20e6-4ace-a68d-1bb20b7da032

**Comment by numz** [comment]
active debug and look into debug folder to check mask composition and see if it missed something or if erode or mask blur is not good enough

**Comment by trxsudo** [comment]
> active debug and look into debug folder to check mask composition and see if it missed something or if erode or mask blur is not good enough

![e944c89cb509df6e627d0a27c1f8f97](https://github.com/numz/sd-wav2lip-uhq/assets/76946041/9a339014-0606-4530-afe4-ac89a20ccffc)


![a7a7ca413fd41b7c5ced07fd0fc4dff](https://github.com/numz/sd-wav2lip-uhq/assets/76946041/d7c8a32f-6f17-4354-b94c-377c3ab2ce8f)

the upper one is the "restored face video" and the bottom one is the "generated video". the "restored face video" has overall better looking eyes but only problem is the rectangular shape which appears around the mouth; however, the "generated video"  looks closer to the 

here are the "restored face video" and the "generated video":

**Comment by numz** [comment]
You can try "only mouth" option, mouton mask dilate something like 30 and "mask blur" between 30 and 60.
Let me know
