### ISSUE TITLE
Crash at the end of image generation

### ISSUE THREAD

**Issue by Niutonian** [numz/sd-wav2lip-uhq#6]
Hello, I installed your extension but sadly after it generates it crashes after the last frame is done.
I'm using Auto 1.5XX

Here is the error output:

Processing frame: 135 of 135 --
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 46, in generate
    w2luhq.execute()
  File "E:\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\wav2lip\wav2lip_uhq.py", line 243, in execute
    cv2.destroyAllWindows()
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1266: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

thanks in advance for your help,

**Comment by numz** [comment]
Hi,
thanks for report,
I see other peaople have this kind of issue: https://github.com/s0md3v/roop/issues/374
try to uninstall opencv-python and reinstall another version of opencv like this :
pip install opencv-python==4.7.0.68 (for exemple),

tell me if it's working please :)

**Comment by numz** [comment]
i make an update, tell me if it works please :)

regards

**Comment by Niutonian** [comment]
Thanks, I will upgrade and report +1

**Comment by Niutonian** [comment]
Hello, it's working great now, I'll close this thread, thanks for the quick update

**Comment by numz** [comment]
thanks for your help :)
