### ISSUE TITLE
无法看到界面及 No module named 'insightface' 错误

### ISSUE THREAD

**Issue by junglehu** [numz/sd-wav2lip-uhq#62]
根据指引进行安装后，报错如下。已经尝试重启WebUI等操作，依旧未能解决。

`Launching Web UI with arguments:
*** Error loading script: ui.py
    Traceback (most recent call last):
      File "E:\AIGC\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AIGC\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AIGC\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 8, in <module>
        from scripts.faceswap.swap import FaceSwap
      File "E:\AIGC\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\faceswap\swap.py", line 6, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: wav2lip_uhq.py
    Traceback (most recent call last):
      File "E:\AIGC\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AIGC\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AIGC\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 11, in <module>
        init_wav2lip_uhq()
      File "E:\AIGC\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 7, in init_wav2lip_uhq
        from ui import on_ui_tabs
      File "E:\AIGC\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 8, in <module>
        from scripts.faceswap.swap import FaceSwap
      File "E:\AIGC\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\faceswap\swap.py", line 6, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'`

**Comment by junglehu** [comment]
已经解决了。
需要先安装 Visual Studio installer，安装组件需要选择C#、python 开发、C++，并且勾选对应系统的SDK（比如Win 11 SDK）；
安装好之后，需要安装insightface： 在正确安装好 Python 3.10 之后，使用 pip install insightface==0.7.3 进行安装。。安装好之后，就可以看到界面了。
