### ISSUE TITLE
AUTO1111`s WebUI dev branch launch error

### ISSUE THREAD

**Issue by rltgjqmcpgjadyd** [numz/sd-wav2lip-uhq#7]
dev branch 60183eebc37a69545e41cb6b00189609b85129b0

sd-wav2lip-uhq launch error

here`s console log

*** Error loading script: ui.py
    Traceback (most recent call last):
      File "J:\SDWebUI\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\SDWebUI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\SDWebUI\extensions\sd-wav2lip-uhq\scripts\ui.py", line 3, in <module>
        from scripts.wav2lip.w2l import W2l
      File "J:\SDWebUI\extensions\sd-wav2lip-uhq\scripts\wav2lip\w2l.py", line 2, in <module>
        import cv2, os, scripts.wav2lip.audio as audio
      File "J:\SDWebUI\extensions\sd-wav2lip-uhq\scripts\wav2lip\audio.py", line 1, in <module>
        import librosa
      File "J:\SDWebUI\venv\Lib\site-packages\librosa\__init__.py", line 211, in <module>
        from . import core
      File "J:\SDWebUI\venv\Lib\site-packages\librosa\core\__init__.py", line 9, in <module>
        from .constantq import *  # pylint: disable=wildcard-import
        ^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\SDWebUI\venv\Lib\site-packages\librosa\core\constantq.py", line 1058, in <module>
        dtype=np.complex,
              ^^^^^^^^^^
      File "J:\SDWebUI\venv\Lib\site-packages\numpy\__init__.py", line 305, in __getattr__
        raise AttributeError(__former_attrs__[attr])
    AttributeError: module 'numpy' has no attribute 'complex'.
    `np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
    The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
        https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

---
*** Error loading script: wav2lip_uhq.py
    Traceback (most recent call last):
      File "J:\SDWebUI\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\SDWebUI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\SDWebUI\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 15, in <module>
        init_wav2lip_uhq()
      File "J:\SDWebUI\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 9, in init_wav2lip_uhq
        from ui import on_ui_tabs
      File "J:\SDWebUI\extensions\sd-wav2lip-uhq\scripts\ui.py", line 3, in <module>
        from scripts.wav2lip.w2l import W2l
      File "J:\SDWebUI\extensions\sd-wav2lip-uhq\scripts\wav2lip\w2l.py", line 2, in <module>
        import cv2, os, scripts.wav2lip.audio as audio
      File "J:\SDWebUI\extensions\sd-wav2lip-uhq\scripts\wav2lip\audio.py", line 1, in <module>
        import librosa
      File "J:\SDWebUI\venv\Lib\site-packages\librosa\__init__.py", line 211, in <module>
        from . import core
      File "J:\SDWebUI\venv\Lib\site-packages\librosa\core\__init__.py", line 9, in <module>
        from .constantq import *  # pylint: disable=wildcard-import
        ^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\SDWebUI\venv\Lib\site-packages\librosa\core\constantq.py", line 1058, in <module>
        dtype=np.complex,
              ^^^^^^^^^^
      File "J:\SDWebUI\venv\Lib\site-packages\numpy\__init__.py", line 305, in __getattr__
        raise AttributeError(__former_attrs__[attr])
    AttributeError: module 'numpy' has no attribute 'complex'.
    `np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
    The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
        https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by numz** [comment]
Hi
, that mean i have to update librosa package....

thanks for report :)

**Comment by numz** [comment]
i update librosa to version 0.10.0.post2

please can you tell me if that fix the issue please?

**Comment by rltgjqmcpgjadyd** [comment]
it`s fixed
everything is working fine
