### ISSUE TITLE
Error with (save)

### ISSUE THREAD

**Issue by boundlessliving** [numz/sd-wav2lip-uhq#70]
When I try to run the process, it processes the frames and then I get this:

Traceback (most recent call last):-
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\sd\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 156, in generate
    video = face_swap.generate()
  File "D:\sd\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\faceswap\swap.py", line 195, in generate
    result = self.swap_face(
  File "D:\sd\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\faceswap\swap.py", line 165, in swap_face
    result_image.save(fn.name)
AttributeError: 'numpy.ndarray' object has no attribute 'save'

**Comment by numz** [comment]
Hi,
It seems to be an issue with numpy package, try to only select sd-wav2lip-uhq in extensions tab and apply and restart.
Numpy can be use in several extensions.
Let me know

**Comment by Starsky-Type** [comment]
Same issue,even close all other extensions

**Comment by katariaak579** [comment]
The issue still persists even after only selecting sd-wav2lip-uhq in extensions
