### ISSUE TITLE
Installation failed, the error message is as follows! 安装失败，错误提示如下！

### ISSUE THREAD

**Issue by jedisun76cn** [numz/sd-wav2lip-uhq#74]
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
 * [new branch]        bump-Pillow-blendmodes-dependency -> origin/bump-Pillow-blendmodes-dependency
   c3d51fc6..35fd24e8  but-report-template -> origin/but-report-template
   102b6617..7d60076b  dev                 -> origin/dev
 * [new branch]        lora_emb_bundle     -> origin/lora_emb_bundle
Already up to date.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\code\sd.webui\system\python\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
*** Error running install.py for extension C:\code\sd.webui\webui\extensions\sd-wav2lip-uhq.
*** Command: "C:\code\sd.webui\system\python\python.exe" "C:\code\sd.webui\webui\extensions\sd-wav2lip-uhq\install.py"
*** Error code: 1
*** stdout: Installing wav2lip_uhq requirement: dlib-bin
*** Installing wav2lip_uhq requirement: opencv-python
*** Installing wav2lip_uhq requirement: pillow
*** Installing wav2lip_uhq requirement: librosa==0.10.0.post2
*** Installing wav2lip_uhq requirement: opencv-contrib-python
*** Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git
***
*** stderr: Traceback (most recent call last):
***   File "C:\code\sd.webui\webui\extensions\sd-wav2lip-uhq\install.py", line 17, in <module>
***     launch.run_pip(f"install {lib}", f"wav2lip_uhq requirement: {lib}")
***   File "C:\code\sd.webui\webui\modules\launch_utils.py", line 138, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "C:\code\sd.webui\webui\modules\launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git.
*** Command: "C:\code\sd.webui\system\python\python.exe" -m pip install git+https://github.com/suno-ai/bark.git --prefer-binary
*** Error code: 2
*** stdout: Collecting git+https://github.com/suno-ai/bark.git
***   Cloning https://github.com/suno-ai/bark.git to c:\users\danie\appdata\local\temp\pip-req-build-t5v206wc
***   Resolved https://github.com/suno-ai/bark.git to commit 773624d26db84278a55aacae9a16d7b25fbccab8
***   Installing build dependencies: started
***   Installing build dependencies: finished with status 'done'
***   Getting requirements to build wheel: started
***   Getting requirements to build wheel: finished with status 'done'
***
*** stderr:   Running command git clone --filter=blob:none --quiet https://github.com/suno-ai/bark.git 'C:\Users\danie\AppData\Local\Temp\pip-req-build-t5v206wc'
*** ERROR: Exception:
*** Traceback (most recent call last):
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
***     status = run_func(*args)
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
***     return func(self, options, args)
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
***     requirement_set = resolver.resolve(
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 73, in resolve
***     collected = self.factory.collect_root_requirements(root_reqs)
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 491, in collect_root_requirements
***     req = self._make_requirement_from_install_req(
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 453, in _make_requirement_from_install_req
***     cand = self._make_candidate_from_link(
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
***     self._link_candidate_cache[link] = LinkCandidate(
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
***     super().__init__(
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
***     self.dist = self._prepare()
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
***     dist = self._prepare_distribution()
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
***     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 538, in prepare_linked_requirement
***     return self._prepare_linked_requirement(req, parallel_builds)
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 653, in _prepare_linked_requirement
***     dist = _get_prepared_distribution(
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
***     abstract_dist.prepare_distribution_metadata(
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 48, in prepare_distribution_metadata
***     self._install_build_reqs(finder)
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 118, in _install_build_reqs
***     build_reqs = self._get_build_requires_wheel()
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 95, in _get_build_requires_wheel
***     return backend.get_requires_for_build_wheel()
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_internal\utils\misc.py", line 697, in get_requires_for_build_wheel
***     return super().get_requires_for_build_wheel(config_settings=cs)
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
***     return self._call_hook('get_requires_for_build_wheel', {
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
***     raise BackendUnavailable(data.get('traceback', ''))
*** pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
***   File "C:\code\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
***     obj = import_module(mod_path)
***   File "importlib\__init__.py", line 126, in import_module
***   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "C:\Users\danie\AppData\Local\Temp\pip-build-env-qh0xdevr\overlay\Lib\site-packages\setuptools\__init__.py", line 13, in <module>
***     from . import version as _version_module
***   File "C:\Users\danie\AppData\Local\Temp\pip-build-env-qh0xdevr\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
***     from ._importlib import metadata
***   File "C:\Users\danie\AppData\Local\Temp\pip-build-env-qh0xdevr\overlay\Lib\site-packages\setuptools\_importlib.py", line 45, in <module>
***     import importlib.metadata as metadata  # noqa: F401
***   File "importlib\metadata\__init__.py", line 17, in <module>
***   File "importlib\metadata\_adapters.py", line 3, in <module>
***   File "email\message.py", line 15, in <module>
***   File "email\utils.py", line 29, in <module>
***   File "socket.py", line 51, in <module>
*** ModuleNotFoundError: No module named '_socket'
***
***
Installing sd-webui-controlnet requirement: changing opencv-python version from 4.7.0.72 to 4.8.0
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.0024733999962336384
Installing requirements for Mov2mov
Installing requirements for imageio-ffmpeg
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Launching Web UI with arguments: --disable-safe-unpickle
Civitai Helper: Get Custom Model Folder
*** Error loading script: ui.py
    Traceback (most recent call last):
      File "C:\code\sd.webui\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\code\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\code\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 7, in <module>
        from scripts.bark.tts import TTS
      File "C:\code\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\bark\tts.py", line 5, in <module>
        from bark.generation import (
    ModuleNotFoundError: No module named 'bark'

---
*** Error loading script: wav2lip_uhq.py
    Traceback (most recent call last):
      File "C:\code\sd.webui\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\code\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\code\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 11, in <module>
        init_wav2lip_uhq()
      File "C:\code\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 7, in init_wav2lip_uhq
        from ui import on_ui_tabs
      File "C:\code\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 7, in <module>
        from scripts.bark.tts import TTS
      File "C:\code\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\bark\tts.py", line 5, in <module>
        from bark.generation import (
    ModuleNotFoundError: No module named 'bark.generation'

**Comment by numz** [comment]
Hi,
For some reson bark doesn"t install on 3.10 6, try to install python 3.10.11

Let me know

Regards

**Comment by jedisun76cn** [comment]
谢谢快速回复！ 我的sd ui 自带环境，里面python 目录，我刚才下载了 python 3.10.11的windows 64bit安装软件，安装好python，然后把python目录覆盖到sd ui 下面的python目录（老的python目录备份了），重启sd ，发现bark和您的插件都安装上去了，但是sd基本绘图功能崩溃了，不得不还原回来备份的python3.10 6的目录，重启sd才能重新绘图。 是否有办法直接能把sd ui里面包含的python升级到指定的3.10.11 版本呢？  还能保持sd绘图的正常。谢谢

**Comment by jedisun76cn** [comment]
Thanks for your quick reply! My SD-UI comes with its own environment, the python directory, I just downloaded python 3.10.11 windows 64bit installation software, installed python, Then overwrite the python directory to the python directory under SD-UI (the old python directory is backed up), restart SD-UI, and find that bark and your extension are installed, but the basic SD drawing function crashed, we have to restore the backup python3.10 6 directory. Restart SD-UI to redraw. Is there a way to directly upgrade python contained in the SD-UI to the specified version 3.10.11? It can also keep SD drawing normally. thank you！ Or can you tell me how to comment out the call and installation of the bark module in the code, because we can directly provide the wav file to drive the wav2lip system to generate video.

**Comment by danielflam** [comment]
Any solution to it not working with the embedded python?
