### ISSUE TITLE
RuntimeError: Torch is not able to use GPU

### ISSUE THREAD

**Issue by prezofpizza** [numz/sd-wav2lip-uhq#81]
After installing the extension I am getting the following error:

Traceback (most recent call last):
  File "D:\WebUiCopy\webui\launch.py", line 48, in <module>
    main()
  File "D:\WebUiCopy\webui\launch.py", line 39, in main
    prepare_environment()
  File "D:\WebUiCopy\webui\modules\launch_utils.py", line 356, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

I setup a clean install of Automatic1111 to see if it was conflicting models or extensions.  

I've been trying for a long while to resolve this and nothing seems to do the trick.

I just want to be sure that the extension is indeed leveraging my NVIDIA GPU (RTX4090) correctly.

Thanks!

**Comment by imdaewoong** [comment]
I also have NVIDIA GPU (RTX4090)and i had the same issue and it wasn't resolved. So I didn't install wav2lip and it worked normally. In my opinion, the moment you install wav2lip, Torch is upgraded and the GPU cannot be used,
and then automatically it changes Torch2.0.1+CU118 to Torch2.1.0+CPU, it does not work and an error occurs. And the production speed slows down significantly. I tested it dozens of times over 5 days, but couldn't solve it. Please resolve this. thank you

**Comment by numz** [comment]
Hi
This issue seems to come from faceswap installation package, but I don't understand when torch2.1.0 is installed in the process because in requirements.txt there is no pytorch package, it seems to come from other requirements.txt that come from onnxruntime or insightface but can't see where, still investigating....
Sorry about that

**Comment by APCOTech** [comment]
> Hi This issue seems to come from faceswap installation package, but I don't understand when torch2.1.0 is installed in the process because in requirements.txt there is no pytorch package, it seems to come from other requirements.txt that come from onnxruntime or insightface but can't see where, still investigating.... Sorry about that

I think it is from Bark

"git checkout 2283dac" for no bark and no face swap 
"git checkout 579d384" for no face swap

Commit 579d384 does the same problem for me, only 2283dac works fine

**Comment by huwhitememes** [comment]
Is there a solve for this?

**Comment by skitzes** [comment]
so this sd extension version of wav2lip just doesn't work? i cant even get sd web ui to open after installing this plugin. this is a shame bc it sounded amazing. will it be fixed soon?

**Comment by prezofpizza** [comment]
I've found that I can get it to work if I open my WebUi folder and use the
Launch shortcut.

I believe it doesn't leverage CUDA or GPU though, but it works. It takes a
while and is cpu intensive. It's a workaround just to tinker with the tool,
not a solution.

**Comment by imdaewoong** [comment]
i'm ok git "checkout 2283dac". i hope use wav2lip with facefusion. thanks

**Comment by imdaewoong** [comment]
i'm ok git checkout e6ee80ada64e59837c2a7a294a3c002d2ad667ac. i'm still hope use wav2lip with facefusion. thanks

**Comment by P-Elendil** [comment]
Confirming I can't find a good workaround at present too making this sadly unfunctional at the moment.

**Comment by APCOTech** [comment]
Finally, it worked for me

**Comment by prezofpizza** [comment]
> Finally, it worked for me

Were you able to use the latest version of the extension with the face swapping?  What did you do that got it working?

**Comment by APCOTech** [comment]
I explained it here... https://github.com/numz/sd-wav2lip-uhq/issues/86

I hope I explained it correctly...
