### ISSUE TITLE
moov atom not found / float division by zero

### ISSUE THREAD

**Issue by GsHeri** [numz/sd-wav2lip-uhq#97]
`Using cuda for inference.
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001a212354e00] moov atom not found
Reading video frames...
Number of frames available for inference: 0
(80, 24515)
Traceback (most recent call last):
  File "F:\Projects\sd-next\venv\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "F:\Projects\sd-next\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\Projects\sd-next\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "F:\Projects\sd-next\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\Projects\sd-next\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\Projects\sd-next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\Projects\sd-next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\Projects\sd-next\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "F:\Projects\sd-next\extensions\sd-wav2lip-uhq\scripts\ui.py", line 160, in generate
    w2l.execute()
  File "F:\Projects\sd-next\extensions\sd-wav2lip-uhq\scripts\wav2lip\w2l.py", line 234, in execute
    mel_idx_multiplier = 80. / fps
ZeroDivisionError: float division by zero`

i don't know what the problem is here. something seems to be wrong with my input video, but the error doesn't give me any more information.
it's a mp4 with 5:06 length.
i have started to work with wav2lip yesterday and successfully processed one other video (which was captured from the same camera, same resolution etc, but it was a lot shorter (9sec for testing).

for this video, i used handbrake to crop the part where the actual mouth movements will be, then saved it with constant framerate and web-optimized mp4.
i've tried it a couple of times now, with new versions of the video, better quality, web-optimized yes/no, different croppings. the audio is exactly as long as the video.

i know moov atom has something to do with corrupted / unfinished video files, but this is definitely not corrupt, since i've re-rendered it multiple times and made sure it completed.

could it be just too long? is there a max length? what else could i try to find out what's wrong here? like i said, a different video clip from the same camera with the same settings worked fine
i appreciate any help

**Comment by numz** [comment]
Hi, 
Sorry about that
It seems to come from the video input file. Can you senf me the file extension or eventually the file itself?

Thanks
